name: hanoi-solution 
version: '0.1' 
summary: Solution for Hanoi Towers 
description: |
  This application shows solution for Hanoi Towers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: icon.png

apps:
  hanoi-solution:
    command: desktop-launch $SNAP/opt/myapp/hanoi_solution
#    desktop: usr/share/applications/desc.desktop
    plugs: [home, unity7, x11]


parts:
  hanoi-solution:
    plugin: qmake
    qt-version: qt5
    project-files: [HanoiSolution.pro]
    source: source
    install: |
     install -d $SNAPCRAFT_PART_INSTALL/opt/myapp
     install hanoi_solution $SNAPCRAFT_PART_INSTALL/opt/myapp/hanoi_solution 
    build-packages:
      - qtdeclarative5-dev
    stage-packages:
      - libqt5qml5
      - libqt5quick5
      - qml-module-qtquick2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
    after: [desktop-qt5]
        
